# Generated by Django 5.0.6 on 2024-05-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_component', '0002_app_category_subcategory_delete_adminapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
    ]
