# Generated by Django 5.0.6 on 2024-05-21 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_component', '0004_appusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='date_downloaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
