databases:
  - name: rewardify_db
    plan: free
    databaseName: rewardify_db
    user: rewardify_project

services:
  - type: web
    plan: free
    name: rewardify_project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn rewardify_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rewardify_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
