# Exported from Render on 2024-05-21T19:06:36Z
services:
  - type: web
    name: rewardify_project-twn6
    runtime: python
    repo: https://github.com/PriyabrataP00/rewardify_project
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
    region: singapore
    buildCommand: ./build.sh
    startCommand: python manage.py runserver
version: "1"
