# Exported from Render on 2024-05-21T18:42:20Z
services:
  - type: web
    name: rewardify_project
    runtime: python
    repo: https://github.com/PriyabrataP00/rewardify_project
    plan: free
    envVars:
      - key: WEB_CONCURRENCY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
    region: singapore
    buildCommand: ./build.sh
    startCommand: python manage.py runserver 10000
version: "1"
